import Head from 'next/head';
import {BsFillMoonFill} from 'react-icons/bs';
import {AiFillGithub, AiFillLinkedin} from "react-icons/ai";
import {SiLeetcode, } from "react-icons/si";
import{RiArrowDropDownLine, RiArrowDropUpLine} from "react-icons/ri";
import{MdOutlineWebAsset} from "react-icons/md";

export default function Home() {
  return (
    <div>
      <Head>
        <title>BotsheloT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/webfavicon.ico" />
      </Head>

      <main className='bg-white'>
        <section className='min-h-screen px-10'>

          <nav className='pt-4 mb-3 flex justify-between'>
            <h1 className='text-xl font-sans font-semibold font'>Botshelo T</h1>
            <ul className='flex items-center'>
              <li> <BsFillMoonFill className='cursor-pointer text-2xl'/> </li>
              <li> <a href='#' className='bg-blue-500 px-3 py-1 rounded-md text-white ml-8 font-medium'>My CV</a> </li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl font-medium text-blue-500'>Botshelo Tlhabanyane</h2>
            <h3 className='font-medium text-2xl'>Software Developer</h3>
            <br/>
            <p className='text-lg text-gray-700'>Ambitious career-focused Computer Science Student based in Johannesburg.<br/> Frontend Developement is what
            interests me the most. I also dable in Backend Developement.
            </p>
          </div>

          <div className='text-4xl text-gray-500'>
            <ul className='flex justify-center gap-9 hover'>
              <li className='hover:text-black'> <a href='https://github.com/BotsheloT' target={'_blank'}><AiFillGithub/></a></li>
              <li className='hover:text-black'> <a href='https://leetcode.com/BotsheloT/' target={'_blank'}><SiLeetcode/></a> </li>
              <li className='hover:text-black'> <a href='https://www.linkedin.com/in/botshelo-tlhabanyane-36b573210/' target={'_blank'}><AiFillLinkedin/></a></li>              
            </ul>
          </div>

          <div className='relative mx-auto bg-gradient-to-b from-blue-500 w-80 h-80 rounded-full mt-5'>
            
          </div>

          <div className='text-center py-10'>
          <h3 className=' font-medium text-2xl'>Why SovTech?</h3>
          <p className='text-lg text-gray-700'>Ever since I was introduced to SovTech, my interest for the company has grown.<br/>
          Through SovTech's Social Media, I have witnessed how seriously they take technology and its potential.<br/> 
          I truly believe that with working at SovTech, I will be surrounded by like-minded and driven people.
            </p>
        </div>
        </section>

      <section className='px-10'>

        <div className='text-center py-10'>
          <h3 className=' font-medium text-2xl'>Skills</h3>
        </div>

        <div className='m-auto items-center text-center py-10'>
          <h3 className='font-medium text-2xl pb-4'>Contact Me</h3>

          <form action = "https://formsubmit.co/botshelotlhabanyane@gmail.com" method ="POST" className='pb-10'>
            <input type={'text'} placeholder = 'Name' className='bg-gray-200 w-72 h-8 rounded-md mb-5 placeholder: pl-2' required/>
            <br/>
            <input type={'email'} placeholder = 'Email Address' className='bg-gray-200 w-72 h-8 rounded-md mb-5 placeholder: pl-2' required/>
            <br/>
            <textarea type={'text'} placeholder = 'Message' className='bg-gray-200 w-72 h-40 rounded-md mb-5 placeholder: pl-2 pt-1' required/>
            <br/>
            <button type="submit" className='bg-blue-500 px-3 py-1 rounded-md text-white text-lg font-medium w-72'> Send Message </button>
          </form>
          
        </div>        

        
      </section>

      <section className=''>

        <footer className='w-full h-72 bg-blue-500 px10 items-center text-center'>
          <h1 className='text-xl text-white pt-10 pb-1 font-medium'>Botshelo T</h1>
          <h2 className='text-base text-white pb-10 font-normal'>Software Developer</h2>

          <a href='#' className='border-solid rounded-md border-white text-white mb-10 w-20 h-10'>Download CV</a>
          
          <div className='text-white flex justify-center gap-10 text-4xl py-10'>
          <a href='https://github.com/BotsheloT' target={'_blank'} className= "hover:text-gray-300"><AiFillGithub/></a>
          <a href='https://leetcode.com/BotsheloT/' target={'_blank'} className= "hover:text-gray-300"><SiLeetcode/></a>
          <a href='https://www.linkedin.com/in/botshelo-tlhabanyane-36b573210/' target={'_blank'} className= "hover:text-gray-300"><AiFillLinkedin/></a>
          </div>          
                    
        </footer>

      </section>
      
      
      </main>

    </div>
  )
}
